name: CI - Build & Test

on:
  workflow_dispatch:
  push:
    branches: [ dev, main ]
    paths: [ "backend/**", "frontend/**", ".github/workflows/**" ]
  pull_request:
    branches: [ main ]
    paths: [ "backend/**", "frontend/**", ".github/workflows/**" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write   # needed for GHCR (frontend)

env:
  # Image repo names (adjust if your registry repos differ)
  BACKEND_IMAGE_NAME: product_service
  FRONTEND_IMAGE_NAME: frontend_app

jobs:
  backend:
    uses: ./.github/workflows/_reusable-build.yml
    with:
      service_name: ${{ env.BACKEND_IMAGE_NAME }}
      context_path: backend
      dockerfile: Dockerfile
      test_command: ""  # e.g. "pip install -r requirements.txt && pytest -q"
      push_image: true
    secrets:
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }} # e.g. shrikesh.azurecr.io
      REGISTRY_USERNAME:     ${{ secrets.ACR_USERNAME }}
      REGISTRY_PASSWORD:     ${{ secrets.ACR_PASSWORD }}

  frontend:
    uses: ./.github/workflows/_reusable-build.yml
    with:
      service_name: ${{ env.FRONTEND_IMAGE_NAME }}
      context_path: frontend
      dockerfile: Dockerfile
      test_command: "npm ci && npm run build && npm test --if-present"
      push_image: true
    secrets:
      REGISTRY_LOGIN_SERVER: ghcr.io
      REGISTRY_USERNAME:     ${{ github.actor }}
      REGISTRY_PASSWORD:     ${{ secrets.GITHUB_TOKEN }}
