name: Frontend CI - Build, Test, & Push Image

on:
  # Manual trigger
  workflow_dispatch:

  # Automatically on pushes to main branch
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml'

env:
  ACR_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js (assuming frontend is Node-based)
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install frontend dependencies and run tests/lint
      working-directory: ./frontend
      run: |
        npm ci  # Clean install
        npm run lint || echo "Linting skipped if no script"  # Assume lint script; add if needed (e.g., ESLint)
        npm test || echo "Tests skipped if no script"  # Assume test script
        npm audit --audit-level moderate  # Security check

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to Azure Container Registry
      run: az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}

    - name: Build and Push Frontend Image
      run: |
        docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }} ./frontend/
        docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }}

    - name: Logout from Azure
      if: always()
      run: az logout